name: main
on: pull_request
jobs:
  build-gcc-15:
    env:
      requires_build:
    runs-on: ubuntu-latest
    steps:
      - name: Load gcc 15 Cache
        uses: actions/cache@v5
        with:
          path: ~/gcc-15
          key: gcc-15-x86_64-pc-linux-gnu
      - name: Create root directory
        if: ${{ hashFiles('~/gcc-15') == '' }}
        run: mkdir ~/gcc-15
      - name: Download sources
        id: source
        if: ${{ hashFiles('~/gcc-15/bin/gcc') == '' }}
        timeout-minutes: 15
        run: 
          curl https://ftp.gnu.org/gnu/gcc/gcc-15.2.0/gcc-15.2.0.tar.gz --output ~/gcc-15/gcc-15.2.0.tar.gz;
          tar -xzf ~/gcc-15/gcc-15.2.0.tar.gz;
          ls;
          mv ~/gcc-15/gcc-15.2.0 ~/gcc-15/src;
          rm ~/gcc-15/gcc-15.2.0.tar.gz;
          echo requires_build=true >> $GITHUB_OUTPUT;
      - name: Download Prerequisites
        timeout-minutes: 15
        working-directory: ~/gcc-15/src
        run: contrib/download_prerequisites
      - name: Create object directory
        if: ${{ hashFiles('~/gcc-15/obj') == '' && steps.source.outputs.requires_build }}
        run: mkdir ~/gcc-15/obj
      - name: Configure
        if: ${{ steps.source.outputs.requires_build }}
        working-directory: ~/gcc-15/obj
        run: ~/gcc-15/src/configure --host=x86_64-pc-linux-gnu --enable-languages=c --prefix=$HOME/gcc-15 --disable-multilib
      - name: Build
        if: ${{ steps.source.outputs.requires_build }}
        working-directory: ~/gcc-15/obj
        timeout-minutes: 120
        run: make -j 8
      - name: Install
        if: ${{ steps.source.outputs.requires_build }}
        working-directory: ~/gcc-15/obj
        run: make install
  build-linux-x86_64-gcc:
    runs-on: ubuntu-latest
    needs: build-gcc-15
    steps:
      - name: Checkout changes
        uses: actions/checkout@v5
      - name: Load Build Caches
        uses: actions/cache@v5
        with:
          path: ~/linux-x86_64-gcc
          key: linux-x86_64-gcc-${{ hashFiles('**/CMakeLists.txt') }}
      - name: Get APT Packages
        uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: libcurl4-openssl-dev clang-19
          version: 0.0.0
      - name: Load gcc 15 Cache
        uses: actions/cache@v5
        with:
          path: ~/gcc-15
          key: gcc-15-x86_64-pc-linux-gnu
      - name: Configure CMake
        run: cmake -B ~/linux-x86_64-gcc -G Ninja -D CMAKE_C_COMPILER=$HOME/gcc-15/bin/gcc
      - name: Build
        run: cmake --build ~/linux-x86_64-gcc -j 8
  build-linux-x86_64-clang:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout changes
        uses: actions/checkout@v5
      - name: Load Build Caches
        uses: actions/cache@v5
        with:
          path: ~/linux-x86_64-clang
          key: linux-x86_64-clang-${{ hashFiles('**/CMakeLists.txt') }}
      - name: Get APT Packages
        uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: libcurl4-openssl-dev clang-19
          version: 0.0.0
      - name: Configure CMake
        run: cmake -B ~/linux-x86_64-clang -G Ninja -D CMAKE_C_COMPILER=clang
      - name: Build
        run: cmake --build ~/linux-x86_64-clang -j 8
  test-linux-x86_64-gcc:
    runs-on: ubuntu-latest
    needs: build-linux-x86_64-gcc
    steps:
      - name: Load Build Caches
        uses: actions/cache@v5
        with:
          path: ~/linux-x86_64-gcc
          key: linux-x86_64-gcc-${{ hashFiles('**/CMakeLists.txt') }}
      - name: Get APT Packages
        uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: libcurl4-openssl-dev clang-19
          version: 0.0.0
      - name: Run Tests
        run: ctest --test-dir ~/linux-x86_64-gcc --output-on-failure
  test-linux-x86_64-clang:
    runs-on: ubuntu-latest
    needs: build-linux-x86_64-clang
    steps:
      - name: Load Build Caches
        uses: actions/cache@v5
        with:
          path: ~/linux-x86_64-clang
          key: linux-x86_64-clang-${{ hashFiles('**/CMakeLists.txt') }}
      - name: Get APT Packages
        uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: libcurl4-openssl-dev clang-19
          version: 0.0.0
      - name: Run Tests
        run: ctest --test-dir ~/linux-x86_64-clang --output-on-failure
